In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('loan_test.csv')
df

,Unnamed: 0,loan_amount,funded_amount,investor_funds,term,interest_rate,installment,grade,sub_grade,emp_length,...,application_type,acc_now_delinq,year,loan_condition,region,complete_date,emp_length_int,income_category,loan_condition_int,interest_payments
0,0,5000,5000,4975.00000,36 months,10.65,162.87,B,B2,10+ years,...,INDIVIDUAL,0.0,2011,Good Loan,munster,01/12/2011,10.0,Low,0,Low
1,1,2500,2500,2500.00000,60 months,15.27,59.83,C,C4,< 1 year,...,INDIVIDUAL,0.0,2011,Bad Loan,leinster,01/12/2011,0.5,Low,1,High
2,2,2400,2400,2400.00000,36 months,15.96,84.33,C,C5,10+ years,...,INDIVIDUAL,0.0,2011,Good Loan,cannught,01/12/2011,10.0,Low,0,High
3,3,10000,10000,10000.00000,36 months,13.49,339.31,C,C1,10+ years,...,INDIVIDUAL,0.0,2011,Good Loan,ulster,01/12/2011,10.0,Low,0,High
4,4,3000,3000,3000.00000,60 months,12.69,67.79,B,B5,1 year,...,INDIVIDUAL,0.0,2011,Good Loan,ulster,01/12/2011,1.0,Low,0,Low
5,5,5000,5000,5000.00000,36 months,7.90,156.46,A,A4,3 years,...,INDIVIDUAL,0.0,2011,Good Loan,munster,01/12/2011,3.0,Low,0,Low
6,6,7000,7000,7000.00000,60 months,15.96,170.08,C,C5,8 years,...,INDIVIDUAL,0.0,2011,Good Loan,leinster,01/12/2011,8.0,Low,0,High
7,7,3000,3000,3000.00000,36 months,18.64,109.43,E,E1,9 years,...,INDIVIDUAL,0.0,2011,Good Loan,ulster,01/12/2011,9.0,Low,0,High
8,8,5600,5600,5600.00000,60 months,21.28,152.39,F,F2,4 years,...,INDIVIDUAL,0.0,2011,Bad Loan,ulster,01/12/2011,4.0,Low,1,High
9,9,5375,5375,5350.00000,60 months,12.69,121.45,B,B5,< 1 year,...,INDIVIDUAL,0.0,2011,Bad Loan,munster,01/12/2011,0.5,Low,1,Low
10,10,6500,6500,6500.00000,60 months,14.65,153.45,C,C3,5 years,...,INDIVIDUAL,0.0,2011,Good Loan,munster,01/12/2011,5.0,Low,0,High
11,11,12000,12000,12000.00000,36 months,12.69,402.54,B,B5,10+ years,...,INDIVIDUAL,0.0,2011,Good Loan,ulster,01/12/2011,10.0,Low,0,Low
12,12,9000,9000,9000.00000,36 months,13.49,305.38,C,C1,< 1 year,...,INDIVIDUAL,0.0,2011,Bad Loan,leinster,01/12/2011,0.5,Low,1,High
13,13,3000,3000,3000.00000,36 months,9.91,96.68,B,B1,3 years,...,INDIVIDUAL,0.0,2011,Good Loan,cannught,01/12/2011,3.0,Low,0,Low
14,14,10000,10000,10000.00000,36 months,10.65,325.74,B,B2,3 years,...,INDIVIDUAL,0.0,2011,Bad Loan,ulster,01/12/2011,3.0,Low,1,Low
15,15,1000,1000,1000.00000,36 months,16.29,35.31,D,D1,< 1 year,...,INDIVIDUAL,0.0,2011,Good Loan,cannught,01/12/2011,0.5,Low,0,High
16,16,10000,10000,10000.00000,36 months,15.27,347.98,C,C4,4 years,...,INDIVIDUAL,0.0,2011,Good Loan,ulster,01/12/2011,4.0,Low,0,High
17,17,3600,3600,3600.00000,36 months,6.03,109.57,A,A1,10+ years,...,INDIVIDUAL,0.0,2011,Good Loan,Northern-Irl,01/12/2011,10.0,Medium,0,Low
18,18,6000,6000,6000.00000,36 months,11.71,198.46,B,B3,1 year,...,INDIVIDUAL,0.0,2011,Good Loan,ulster,01/12/2011,1.0,Low,0,Low
19,19,9200,9200,9200.00000,36 months,6.03,280.01,A,A1,6 years,...,INDIVIDUAL,0.0,2011,Good Loan,ulster,01/12/2011,6.0,Low,0,Low
20,20,20250,20250,19142.16108,60 months,15.27,484.63,C,C4,3 years,...,INDIVIDUAL,0.0,2011,Good Loan,munster,01/12/2011,3.0,Low,0,High
21,21,21000,21000,21000.00000,36 months,12.42,701.73,B,B4,10+ years,...,INDIVIDUAL,0.0,2011,Bad Loan,leinster,01/12/2011,10.0,Medium,1,Low
22,22,10000,10000,10000.00000,36 months,11.71,330.76,B,B3,10+ years,...,INDIVIDUAL,0.0,2011,Good Loan,munster,01/12/2011,10.0,Low,0,Low
23,23,10000,10000,10000.00000,36 months,11.71,330.76,B,B3,5 years,...,INDIVIDUAL,0.0,2011,Good Loan,ulster,01/12/2011,5.0,Low,0,Low
24,24,6000,6000,6000.00000,36 months,11.71,198.46,B,B3,1 year,...,INDIVIDUAL,0.0,2011,Bad Loan,ulster,01/12/2011,1.0,Low,1,Low
25,25,15000,15000,15000.00000,36 months,9.91,483.38,B,B1,2 years,...,INDIVIDUAL,0.0,2011,Good Loan,cannught,01/12/2011,2.0,Low,0,Low
26,26,15000,15000,8725.00000,36 months,14.27,514.64,C,C2,9 years,...,INDIVIDUAL,0.0,2011,Bad Loan,Northern-Irl,01/12/2011,9.0,Low,1,High
27,27,5000,5000,5000.00000,60 months,16.77,123.65,D,D2,2 years,...,INDIVIDUAL,0.0,2011,Bad Loan,Northern-Irl,01/12/2011,2.0,Low,1,High
28,28,4000,4000,4000.00000,36 months,11.71,132.31,B,B3,10+ years,...,INDIVIDUAL,0.0,2011,Good Loan,leinster,01/12/2011,10.0,Medium,0,Low
29,29,8500,8500,8500.00000,36 months,11.71,281.15,B,B3,< 1 year,...,INDIVIDUAL,0.0,2011,Good Loan,cannught,01/12/2011,0.5,Low,0,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887349,887349,20000,20000,20000.00000,36 months,6.99,617.46,A,A3,2 years,...,INDIVIDUAL,0.0,2015,Good Loan,leinster,01/01/2015,2.0,Low,0,Low
887350,887350,10300,10300,10300.00000,60 months,13.66,237.86,C,C3,10+ years,...,INDIVIDUAL,0.0,2015,Good Loan,ulster,01/01/2015,10.0,Low,0,High
887351,887351,4200,4200,4200.00000,36 months,15.99,147.64,D,D2,10+ years,...,INDIVIDUAL,0.0,2015,Bad Loan,ulster,01/01/2015,10.0,Low,1,High
887352,887352,15000,15000,15000.00000,36 months,11.99,498.15,B,B5,< 1 year,...,INDIVIDUAL,0.0,2015,Good Loan,Northern-Irl,01/01/2015,0.5,Low,0,Low
887353,887353,15000,15000,15000.00000,60 months,11.44,329.44,B,B4,4 years,...,INDIVIDUAL,0.0,2015,Good Loan,leinster,01/01/2015,4.0,Low,0,Low
887354,887354,6000,6000,6000.00000,36 months,17.86,216.50,D,D5,10+ years,...,INDIVIDUAL,0.0,2015,Good Loan,leinster,01/01/2015,10.0,Low,0,High
887355,887355,26950,26950,26950.00000,36 months,8.19,846.88,A,A5,NaN,...,INDIVIDUAL,0.0,2015,Good Loan,ulster,01/01/2015,NaN,Low,0,Low
887356,887356,23000,23000,23000.00000,60 months,15.59,554.32,D,D1,10+ years,...,INDIVIDUAL,0.0,2015,Good Loan,ulster,01/01/2015,10.0,Low,0,High
887357,887357,18700,18700,18700.00000,60 months,17.86,473.44,D,D5,10+ years,...,INDIVIDUAL,0.0,2015,Good Loan,leinster,01/01/2015,10.0,Low,0,High
887358,887358,25000,25000,25000.00000,60 months,15.99,607.82,D,D2,3 years,...,INDIVIDUAL,0.0,2015,Good Loan,leinster,01/01/2015,3.0,Medium,0,High
887359,887359,25000,25000,25000.00000,60 months,15.59,602.52,D,D1,NaN,...,INDIVIDUAL,0.0,2015,Good Loan,cannught,01/01/2015,NaN,Low,0,High
887360,887360,26500,26500,26500.00000,60 months,8.67,545.87,B,B1,10+ years,...,INDIVIDUAL,0.0,2015,Good Loan,Northern-Irl,01/01/2015,10.0,Low,0,Low
887361,887361,21000,21000,21000.00000,36 months,6.03,639.15,A,A1,10+ years,...,INDIVIDUAL,0.0,2015,Good Loan,Northern-Irl,01/01/2015,10.0,Low,0,Low
887362,887362,8000,8000,8000.00000,36 months,8.19,251.40,A,A5,9 years,...,INDIVIDUAL,0.0,2015,Good Loan,munster,01/01/2015,9.0,Low,0,Low
887363,887363,12000,12000,12000.00000,36 months,9.49,384.34,B,B2,4 years,...,INDIVIDUAL,0.0,2015,Good Loan,ulster,01/01/2015,4.0,Low,0,Low
887364,887364,10775,10775,10775.00000,36 months,6.03,327.95,A,A1,< 1 year,...,INDIVIDUAL,0.0,2015,Good Loan,leinster,01/01/2015,0.5,Low,0,Low
887365,887365,7000,7000,7000.00000,36 months,14.31,240.30,C,C4,10+ years,...,INDIVIDUAL,0.0,2015,Good Loan,cannught,01/01/2015,10.0,Low,0,High
887366,887366,6225,6225,6225.00000,36 months,16.49,220.37,D,D3,2 years,...,INDIVIDUAL,0.0,2015,Good Loan,leinster,01/01/2015,2.0,Low,0,High
887367,887367,10000,10000,10000.00000,36 months,6.49,306.45,A,A2,1 year,...,INDIVIDUAL,0.0,2015,Good Loan,leinster,01/01/2015,1.0,Low,0,Low
887368,887368,13150,13150,13150.00000,60 months,14.99,312.77,C,C5,8 years,...,INDIVIDUAL,0.0,2015,Good Loan,leinster,01/01/2015,8.0,Low,0,High
887369,887369,4000,4000,4000.00000,36 months,8.67,126.59,B,B1,10+ years,...,INDIVIDUAL,0.0,2015,Good Loan,ulster,01/01/2015,10.0,Low,0,Low
887370,887370,7500,7500,7500.00000,36 months,9.49,240.22,B,B2,8 years,...,INDIVIDUAL,0.0,2015,Good Loan,cannught,01/01/2015,8.0,Low,0,Low
887371,887371,10850,10850,10850.00000,36 months,19.24,399.04,E,E2,NaN,...,INDIVIDUAL,0.0,2015,Bad Loan,cannught,01/01/2015,NaN,Low,1,High
887372,887372,12000,12000,12000.00000,36 months,11.99,398.52,B,B5,< 1 year,...,INDIVIDUAL,0.0,2015,Good Loan,cannught,01/01/2015,0.5,Low,0,Low
887373,887373,11575,11575,11575.00000,36 months,15.59,404.61,D,D1,10+ years,...,INDIVIDUAL,0.0,2015,Good Loan,munster,01/01/2015,10.0,Low,0,High
887374,887374,10000,10000,10000.00000,36 months,11.99,332.10,B,B5,8 years,...,INDIVIDUAL,0.0,2015,Good Loan,ulster,01/01/2015,8.0,Low,0,Low
887375,887375,24000,24000,24000.00000,36 months,11.99,797.03,B,B5,10+ years,...,INDIVIDUAL,0.0,2015,Good Loan,Northern-Irl,01/01/2015,10.0,Low,0,Low
887376,887376,13000,13000,13000.00000,60 months,15.99,316.07,D,D2,5 years,...,INDIVIDUAL,0.0,2015,Good Loan,leinster,01/01/2015,5.0,Low,0,High
887377,887377,12000,12000,12000.00000,60 months,19.99,317.86,E,E3,1 year,...,INDIVIDUAL,0.0,2015,Good Loan,Northern-Irl,01/01/2015,1.0,Low,0,High
887378,887378,20000,20000,20000.00000,36 months,11.99,664.20,B,B5,10+ years,...,INDIVIDUAL,0.0,2015,Good Loan,leinster,01/01/2015,10.0,Low,0,Low

In [3]:
a = {'10+ years':1,'< 1 year':2, '1 year':3, '3 years':4, '8 years':5,
          '9 years':6,'4 years':7,'5 years':8,'6 years':9, '2 years': 10, '7 years':11, 'nan': 12}

df['emp_length_cat'] = df.emp_length.map(a)

In [4]:
df[['emp_length', 'emp_length_cat']]

       emp_length  emp_length_cat
0       10+ years             1.0
1        < 1 year             2.0
2       10+ years             1.0
3       10+ years             1.0
4          1 year             3.0
5         3 years             4.0
6         8 years             5.0
7         9 years             6.0
8         4 years             7.0
9        < 1 year             2.0
10        5 years             8.0
11      10+ years             1.0
12       < 1 year             2.0
13        3 years             4.0
14        3 years             4.0
15       < 1 year             2.0
16        4 years             7.0
17      10+ years             1.0
18         1 year             3.0
19        6 years             9.0
20        3 years             4.0
21      10+ years             1.0
22      10+ years             1.0
23        5 years             8.0
24         1 year             3.0
25        2 years            10.0
26        9 years             6.0
27        2 years            10.0
28      10+ years             1.0
29       < 1 year             2.0
...           ...             ...
887349    2 years            10.0
887350  10+ years             1.0
887351  10+ years             1.0
887352   < 1 year             2.0
887353    4 years             7.0
887354  10+ years             1.0
887355        NaN             NaN
887356  10+ years             1.0
887357  10+ years             1.0
887358    3 years             4.0
887359        NaN             NaN
887360  10+ years             1.0
887361  10+ years             1.0
887362    9 years             6.0
887363    4 years             7.0
887364   < 1 year             2.0
887365  10+ years             1.0
887366    2 years            10.0
887367     1 year             3.0
887368    8 years             5.0
887369  10+ years             1.0
887370    8 years             5.0
887371        NaN             NaN
887372   < 1 year             2.0
887373  10+ years             1.0
887374    8 years             5.0
887375  10+ years             1.0
887376    5 years             8.0
887377     1 year             3.0
887378  10+ years             1.0

[887379 rows x 2 columns]

In [5]:
df['emp_length_cat'].fillna(value = df['emp_length_cat'].median(), inplace = True)

In [6]:
df.emp_length_cat

0          1.0
1          2.0
2          1.0
3          1.0
4          3.0
5          4.0
6          5.0
7          6.0
8          7.0
9          2.0
10         8.0
11         1.0
12         2.0
13         4.0
14         4.0
15         2.0
16         7.0
17         1.0
18         3.0
19         9.0
20         4.0
21         1.0
22         1.0
23         8.0
24         3.0
25        10.0
26         6.0
27        10.0
28         1.0
29         2.0
          ...
887349    10.0
887350     1.0
887351     1.0
887352     2.0
887353     7.0
887354     1.0
887355     4.0
887356     1.0
887357     1.0
887358     4.0
887359     4.0
887360     1.0
887361     1.0
887362     6.0
887363     7.0
887364     2.0
887365     1.0
887366    10.0
887367     3.0
887368     5.0
887369     1.0
887370     5.0
887371     4.0
887372     2.0
887373     1.0
887374     5.0
887375     1.0
887376     8.0
887377     3.0
887378     1.0
Name: emp_length_cat, Length: 887379, dtype: float64